name: Mac Rebuild Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build test image
      run: |
        docker build -f tests/Dockerfile -t mac-rebuild:test .

    - name: Run tests
      run: |
        docker run --rm mac-rebuild:test test

    - name: Test plugin system
      run: |
        docker run --rm mac-rebuild:test sh -c "mac-rebuild plugins"

    - name: Test backup command
      run: |
        docker run --rm -e MAC_REBUILD_NON_INTERACTIVE=1 mac-rebuild:test sh -c "mac-rebuild backup --help"

    - name: Test version command
      run: |
        docker run --rm mac-rebuild:test sh -c "mac-rebuild --version"

  integration-test:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run integration tests
      run: |
        docker build -f tests/Dockerfile -t mac-rebuild:integration .
        docker run --rm -v $(pwd)/tests:/tests mac-rebuild:integration sh -c "
          cd /tests && 
          bash integration-tests.sh
        "

  security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run ShellCheck
      run: |
        sudo apt-get update && sudo apt-get install -y shellcheck
        find . -name "*.sh" -type f -exec shellcheck {} \;
        shellcheck mac-rebuild
